import { Validators } from '@angular/forms';

export class SearchFilterConstants {

public static SEARCH_FIELDS = {
    siteId:[null],
    lienId:[null],
    firstName:[null],
    lastName:[null],
    ssn:[null,[Validators.minLength(9), Validators.maxLength(9)]],
    irCaseId:[null],
    lienTypeCd:[null],
    lienPriorityCd:[null],
    workflowStatusCode:[null],
    recordStatusCode:[null],
    updatedBy:[null],
    associateId:[null],
    priority:[null],
    courtOrderState:[null],
    originalOrCopy:[null],
    deleteType:[null],
    eiwoRecords:[null],
    interrogatory:[null],
    indexedForm:[null],
    indexedTill:[null],
    deleteFrom:[null],
    deleteTill:[null],
    releaseOrder:[null],
    needInfo:[null],
    branchCode:[null],
    companyCode:[null],
    payrollFileNumber:[null],
    adpEmployeeIdentifier:[null],
    deleteCommentCode:[null],
    userId:[null]
}

public static WORK_FLOW_STATUS_DROP_DOWN = [
    { description: 'New', code: 'NE' },
    { description: 'PQ To Be Transmitted', code: 'B' },
    { description: 'PQ Transmitted', code: 'D' },
    { description: 'PQ Re-Transmitted', code: 'PR' },
    { description: 'PQ Validation Error', code: 'PV' },
    { description: 'PQ Missing Records', code: 'PM' },
    { description: 'PQ Extra Records', code: 'PE' },
    { description: 'PQ UTL Pending', code: 'PP' },
    { description: 'PQ UTL Complete', code: 'PU' },
    { description: 'Change Request', code: 'CR' },
    { description: 'Transmitting', code: 'TR' },
    { description: 'Rules Ready', code: 'RR' },
    { description: 'Review', code: 'RF' },
    { description: 'Audit', code: 'RS' },
    { description: 'Completed', code: 'CO' },
    { description: 'Acknowledgement SENT', code: 'AS' },
    { description: 'Exception', code: 'ME' },
    { description: 'Load Error', code: 'LE' },
    { description: 'Load Review', code: 'LR' },
    { description: 'Worker Exception', code: 'WE' },
    { description: 'NMI Answered', code: 'NA' },
    { description: 'In Tickler', code: 'IT' },
    { description: 'Ready For Review', code: 'RW' },
    { description: 'Rejected', code: 'RJ' },
    { description: 'Re-Submitted', code: 'RE' },
    { description: 'Ready For Audit', code: 'RA' },
    { description: 'Index Only', code: 'O' },
    { description: 'Imported Data', code: 'HR' },
    { description: 'Tier 2 Research', code: 'T2' },
    { description: 'Transmitting Audit', code: 'TA' }
]
  }